# Generated by Django 3.2.13 on 2023-11-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='backet_history',
            new_name='basket_history',
        ),
    ]
